import { AXIS_NAMES } from '../constants';
import { DetectedDevice, MappingState, InputType, AxisCalibrationType } from '../types';

export const generateXml = (
  allDevices: DetectedDevice[],
  mappings: MappingState
): string => {
  const allMappingsFlat = Object.values(mappings).flat();
  const usedDeviceGuids = Array.from(new Set(allMappingsFlat.map(m => m.deviceGuid)));
  const usedDevices = allDevices.filter(d => usedDeviceGuids.includes(d.guid));

  const deviceIndexMap: Record<string, number> = {};
  usedDevices.forEach((d, i) => {
    deviceIndexMap[d.guid] = i;
  });

  let xml = `<?xml version="1.0" encoding="UTF-8" ?>\n`;
  xml += `<!-- Generated by DiRT Rally Web Mapper (Visual Configurator) -->\n`;
  
  const deviceAttributes = usedDevices
    .map((d, i) => `device_type_${i}="${d.guid}"`)
    .join(' ');

  xml += `<ActionMap name="custom_mapper" ${deviceAttributes} priority="0" shouldbindalldevicetypes="true">\n`;

  Object.entries(mappings).forEach(([actionId, actionMappings]) => {
    xml += `  <Action id="${actionId}">\n`;

    actionMappings.forEach(mapping => {
        let inputId = '';
        if (mapping.type === InputType.AXIS) {
          inputId = AXIS_NAMES[mapping.index] || `di_axis_${mapping.index}`;
        } else {
          inputId = `di_button_${mapping.index}`;
        }

        const attributes: string[] = [`id="${inputId}"`];

        if (mapping.type === InputType.AXIS) {
          // Use user-defined calibration or sensible defaults
          const calibration = mapping.calibration || 'uniDirPos';
          attributes.push(`type="${calibration}"`);
          attributes.push(`deadzone="${mapping.deadzone ?? '0.0'}"`);
          attributes.push(`saturation="${mapping.saturation ?? '1.0'}"`);
        }

        const devIndex = deviceIndexMap[mapping.deviceGuid];
        if (devIndex !== undefined && devIndex > 0) {
          attributes.push(`restricted_device="${mapping.deviceGuid}"`);
        }

        xml += `    <Axis ${attributes.join(' ')} />\n`;
    });

    xml += `  </Action>\n`;
  });

  xml += `</ActionMap>`;
  return xml;
};
